package riichinexus.microservices.club.router
import riichinexus.system.api.RegisteredAPIMessage

import riichinexus.system.json.JsonCodecs.given
import riichinexus.microservices.club.api.*
import riichinexus.microservices.club.objects.clubmanagement.*
import riichinexus.microservices.club.objects.membershipmanagement.*
import riichinexus.microservices.club.objects.rankprivilegemanagement.*
import riichinexus.microservices.club.objects.relationmanagement.*
import riichinexus.microservices.club.objects.tournamentparticipation.*
import riichinexus.microservices.club.objects.clubmanagement.apiTypes.*
import riichinexus.microservices.club.objects.membershipmanagement.apiTypes.*
import riichinexus.microservices.club.objects.rankprivilegemanagement.apiTypes.*
import riichinexus.microservices.club.objects.relationmanagement.apiTypes.*
import riichinexus.microservices.club.objects.tournamentparticipation.apiTypes.*
import riichinexus.microservices.club.objects.auditreadmodel.apiTypes.*
import riichinexus.microservices.player.objects.apiTypes.*
import riichinexus.microservices.notification.objects.Notification
import riichinexus.system.objects.PagedResponse
import riichinexus.microservices.tournament.objects.lineupmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.paifumanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.recordmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.rulesmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.settlementmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.tablemanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.tournamentmanagement.apiTypes.*

object ClubAPIMessageRegistry:

  val apiMessages: Vector[RegisteredAPIMessage] =
    Vector(
      RegisteredAPIMessage.api[ClubPrivilegeDefinitionsAPIMessage, Vector[ClubPrivilegeDefinition]],
      RegisteredAPIMessage.api[ListClubsAPIMessage, PagedResponse[ClubView]],
      RegisteredAPIMessage.api[GetClubAPIMessage, ClubView],
      RegisteredAPIMessage.api[ListPublicClubsAPIMessage, PagedResponse[PublicClubDirectoryEntry]],
      RegisteredAPIMessage.api[GetPublicClubAPIMessage, PublicClubDetailView],
      RegisteredAPIMessage.api[PublicClubLeaderboardAPIMessage, PagedResponse[ClubLeaderboardEntry]],
      RegisteredAPIMessage.created[CreateClubAPIMessage, ClubView],
      RegisteredAPIMessage.api[ListClubTournamentsAPIMessage, PagedResponse[ClubTournamentParticipationView]],
      RegisteredAPIMessage.api[ListClubMembersAPIMessage, PagedResponse[PlayerProfileView]],
      RegisteredAPIMessage.api[ListClubMemberPrivilegesAPIMessage, PagedResponse[ClubMemberPrivilegeSnapshotView]],
      RegisteredAPIMessage.api[GetClubMemberPrivilegeAPIMessage, ClubMemberPrivilegeSnapshotView],
      RegisteredAPIMessage.api[ListClubContributionAuditsAPIMessage, PagedResponse[ClubContributionAuditEntry]],
      RegisteredAPIMessage.api[AddClubMemberAPIMessage, ClubView],
      RegisteredAPIMessage.api[RemoveClubMemberAPIMessage, ClubView],
      RegisteredAPIMessage.api[AssignClubAdminAPIMessage, ClubView],
      RegisteredAPIMessage.api[RevokeClubAdminAPIMessage, ClubView],
      RegisteredAPIMessage.api[AssignClubTitleAPIMessage, ClubView],
      RegisteredAPIMessage.api[ClearClubTitleAPIMessage, ClubView],
      RegisteredAPIMessage.api[AdjustClubTreasuryAPIMessage, ClubView],
      RegisteredAPIMessage.api[AdjustClubPointPoolAPIMessage, ClubView],
      RegisteredAPIMessage.api[AdjustClubMemberContributionAPIMessage, ClubView],
      RegisteredAPIMessage.api[UpdateClubRankTreeAPIMessage, ClubView],
      RegisteredAPIMessage.api[AwardClubHonorAPIMessage, ClubView],
      RegisteredAPIMessage.api[RevokeClubHonorAPIMessage, ClubView],
      RegisteredAPIMessage.api[UpdateClubRecruitmentPolicyAPIMessage, ClubView],
      RegisteredAPIMessage.api[UpdateClubRelationAPIMessage, ClubView],
      RegisteredAPIMessage.accepted[SubmitClubRelationRequestAPIMessage, Vector[Notification]],
      RegisteredAPIMessage.api[ListClubApplicationsAPIMessage, PagedResponse[ClubMembershipApplicationView]],
      RegisteredAPIMessage.api[GetCurrentClubApplicationAPIMessage, ClubMembershipApplicationView],
      RegisteredAPIMessage.api[GetClubApplicationAPIMessage, ClubMembershipApplicationView],
      RegisteredAPIMessage.api[SubmitClubApplicationAPIMessage, ClubMembershipApplicationResponse],
      RegisteredAPIMessage.api[WithdrawClubApplicationAPIMessage, ClubMembershipApplicationResponse],
      RegisteredAPIMessage.api[ReviewClubApplicationAPIMessage, ClubMembershipApplicationView],
      RegisteredAPIMessage.api[ApproveClubApplicationAPIMessage, ClubView],
      RegisteredAPIMessage.api[RejectClubApplicationAPIMessage, ClubView],
      RegisteredAPIMessage.api[AcceptClubTournamentAPIMessage, TournamentMutationView],
      RegisteredAPIMessage.api[DeclineClubTournamentAPIMessage, TournamentMutationView]
    )
