package api.contracts

object ApiContracts:
  export _root_.riichinexus.api.{
    AcknowledgeDomainEventOutboxRequest,
    AddClubMemberRequest,
    AdjustClubMemberContributionRequest,
    AdjustClubPointPoolRequest,
    AdjustClubTreasuryRequest,
    AdjudicateAppealRequest,
    AdvanceKnockoutStageRequest,
    ApiError,
    ApiMessage,
    ApproveClubApplicationRequest,
    AssignClubAdminRequest,
    AssignClubTitleRequest,
    AssignTournamentAdminRequest,
    AwardClubHonorRequest,
    BanPlayerRequest,
    BatchAcknowledgeDomainEventOutboxRequest,
    BatchQuarantineDomainEventOutboxRequest,
    BatchReplayDomainEventOutboxRequest,
    ClearClubTitleRequest,
    ClubMembershipApplicationRequest,
    ClubRankNodeRequest,
    CompleteStageRequest,
    ConfigureStageRulesRequest,
    CreateClubRequest,
    CreateGuestSessionRequest,
    CreatePlayerRequest,
    CreateTournamentRequest,
    CreateTournamentStageRequest,
    DissolveClubRequest,
    FileAppealRequest,
    FinalizeTournamentSettlementRequest,
    ForceResetTableRequest,
    GrantSuperAdminRequest,
    HealthResponse,
    OperatorRequest,
    PagedResponse,
    ProcessAdvancedStatsTasksRequest,
    ProcessDictionaryNamespaceRemindersRequest,
    QuarantineDomainEventOutboxRequest,
    RecomputeAdvancedStatsRequest,
    RejectClubApplicationRequest,
    ReplayDomainEventOutboxRequest,
    ReopenAppealRequest,
    RequestDictionaryNamespaceRequest,
    ResolveAppealRequest,
    RevokeClubHonorRequest,
    RevokeDictionaryNamespaceRequest,
    RevokeGuestSessionRequest,
    ReviewClubApplicationRequest,
    ReviewDictionaryNamespaceRequest,
    SettleTournamentRequest,
    SettlementAdjustmentRequest,
    StageLineupSeatRequest,
    SubmitStageLineupRequest,
    TransferDictionaryNamespaceRequest,
    UpdateAppealWorkflowRequest,
    UpdateClubRankTreeRequest,
    UpdateClubRecruitmentPolicyRequest,
    UpdateClubRelationRequest,
    UpdateDictionaryNamespaceCollaboratorsRequest,
    UpdateDictionaryNamespaceContextRequest,
    UpdateTableSeatStateRequest,
    UpgradeGuestSessionRequest,
    UploadPaifuRequest,
    UpsertDictionaryRequest,
    WithdrawClubApplicationRequest
  }

object JsonSupport:
  export _root_.riichinexus.api.ApiModels.given
  export _root_.json.JsonCodecs.given
