package riichinexus.infrastructure.memory

type InMemoryPlayerRepository = _root_.database.memory.InMemoryPlayerRepository
type InMemoryGuestSessionRepository = _root_.database.memory.InMemoryGuestSessionRepository
type InMemoryClubRepository = _root_.database.memory.InMemoryClubRepository
type InMemoryTournamentRepository = _root_.database.memory.InMemoryTournamentRepository
type InMemoryTableRepository = _root_.database.memory.InMemoryTableRepository
type InMemoryMatchRecordRepository = _root_.database.memory.InMemoryMatchRecordRepository
type InMemoryPaifuRepository = _root_.database.memory.InMemoryPaifuRepository
type InMemoryAppealTicketRepository = _root_.database.memory.InMemoryAppealTicketRepository
type InMemoryDashboardRepository = _root_.database.memory.InMemoryDashboardRepository
type InMemoryAdvancedStatsBoardRepository = _root_.database.memory.InMemoryAdvancedStatsBoardRepository
type InMemoryAdvancedStatsRecomputeTaskRepository = _root_.database.memory.InMemoryAdvancedStatsRecomputeTaskRepository
type InMemoryGlobalDictionaryRepository = _root_.database.memory.InMemoryGlobalDictionaryRepository
type InMemoryDictionaryNamespaceRepository = _root_.database.memory.InMemoryDictionaryNamespaceRepository
type InMemoryTournamentSettlementRepository = _root_.database.memory.InMemoryTournamentSettlementRepository
type InMemoryEventCascadeRecordRepository = _root_.database.memory.InMemoryEventCascadeRecordRepository
type InMemoryDomainEventOutboxRepository = _root_.database.memory.InMemoryDomainEventOutboxRepository
type InMemoryDomainEventDeliveryReceiptRepository = _root_.database.memory.InMemoryDomainEventDeliveryReceiptRepository
type InMemoryDomainEventSubscriberCursorRepository = _root_.database.memory.InMemoryDomainEventSubscriberCursorRepository
type InMemoryAuditEventRepository = _root_.database.memory.InMemoryAuditEventRepository
type InMemoryDomainEventBus = _root_.database.memory.InMemoryDomainEventBus
