package riichinexus.microservices.tournament.router
import riichinexus.api.functions.RegisteredAPIMessageFunctions

import riichinexus.api.RegisteredAPIMessage
import riichinexus.infrastructure.json.JsonCodecs.given
import riichinexus.microservices.tournament.api.*
import riichinexus.microservices.tournament.objects.rulesmanagement.knockout.KnockoutBracketSnapshot
import riichinexus.microservices.tournament.objects.paifumanagement.Paifu
import riichinexus.microservices.tournament.objects.rulesmanagement.stageprogression.StageAdvancementSnapshot
import riichinexus.microservices.tournament.objects.rulesmanagement.ranking.StageRankingSnapshot
import riichinexus.microservices.tournament.objects.tournamentmanagement.TournamentWhitelistEntry
import riichinexus.microservices.tournament.objects.lineupmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.paifumanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.recordmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.rulesmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.settlementmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.tablemanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.tournamentmanagement.apiTypes.*
import riichinexus.microservices.tournament.objects.tournamentmanagement.apiTypes.AssignTournamentAdminRequest.given
import riichinexus.system.objects.PagedResponse

object TournamentAPIMessageRegistry:

  val apiMessages: Vector[RegisteredAPIMessage] =
    Vector(
      RegisteredAPIMessageFunctions.api[TournamentListAPIMessage, PagedResponse[TournamentSummaryView]],
      RegisteredAPIMessageFunctions.api[TournamentGetAPIMessage, TournamentDetailView],
      RegisteredAPIMessageFunctions.api[ListPublicSchedulesAPIMessage, PagedResponse[PublicScheduleView]],
      RegisteredAPIMessageFunctions.api[ListPublicTournamentsAPIMessage, PagedResponse[PublicTournamentSummaryView]],
      RegisteredAPIMessageFunctions.api[GetPublicTournamentAPIMessage, PublicTournamentDetailView],
      RegisteredAPIMessageFunctions.api[TournamentStageDirectoryAPIMessage, Vector[TournamentStageDirectoryEntry]],
      RegisteredAPIMessageFunctions.api[TournamentWhitelistListAPIMessage, PagedResponse[TournamentWhitelistEntry]],
      RegisteredAPIMessageFunctions.api[TournamentSettlementListAPIMessage, PagedResponse[TournamentSettlementView]],
      RegisteredAPIMessageFunctions.api[TournamentSettlementGetAPIMessage, TournamentSettlementView],
      RegisteredAPIMessageFunctions.created[TournamentCreateAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentPublishAPIMessage, TournamentMutationView],
      RegisteredAPIMessageFunctions.api[TournamentStartAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentSettleAPIMessage, TournamentSettlementView],
      RegisteredAPIMessageFunctions.api[TournamentSettlementFinalizeAPIMessage, TournamentSettlementView],
      RegisteredAPIMessageFunctions.api[TournamentRegisterPlayerAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentRegisterClubAPIMessage, TournamentMutationView],
      RegisteredAPIMessageFunctions.api[TournamentRemoveClubParticipationAPIMessage, TournamentMutationView],
      RegisteredAPIMessageFunctions.api[TournamentWhitelistPlayerAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentWhitelistClubAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentAssignAdminAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentRevokeAdminAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentStageCreateAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentStageConfigureRulesAPIMessage, TournamentSummaryView],
      RegisteredAPIMessageFunctions.api[TournamentStageSubmitLineupAPIMessage, TournamentMutationView],
      RegisteredAPIMessageFunctions.api[TournamentStageScheduleTablesAPIMessage, TournamentMutationView],
      RegisteredAPIMessageFunctions.api[TournamentStageStandingsAPIMessage, StageRankingSnapshot],
      RegisteredAPIMessageFunctions.api[TournamentStageTablesAPIMessage, PagedResponse[TournamentTableView]],
      RegisteredAPIMessageFunctions.api[TournamentStageAdvancementPreviewAPIMessage, StageAdvancementSnapshot],
      RegisteredAPIMessageFunctions.api[TournamentStageKnockoutBracketAPIMessage, KnockoutBracketSnapshot],
      RegisteredAPIMessageFunctions.api[TournamentStageAdvanceAPIMessage, Vector[TournamentTableView]],
      RegisteredAPIMessageFunctions.api[TournamentStageCompleteAPIMessage, StageAdvancementSnapshot],
      RegisteredAPIMessageFunctions.api[TournamentTableListAPIMessage, PagedResponse[TournamentTableView]],
      RegisteredAPIMessageFunctions.api[TournamentTableGetAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentTableUpdateSeatStateAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentTableUpdateOwnReadyAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentTableStartAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentTableUploadPaifuAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentTableResetAPIMessage, TournamentTableView],
      RegisteredAPIMessageFunctions.api[TournamentRecordListAPIMessage, PagedResponse[TournamentMatchRecordView]],
      RegisteredAPIMessageFunctions.api[TournamentRecordGetAPIMessage, TournamentMatchRecordView],
      RegisteredAPIMessageFunctions.api[TournamentRecordGetByTableAPIMessage, TournamentMatchRecordView],
      RegisteredAPIMessageFunctions.api[TournamentPaifuListAPIMessage, PagedResponse[PaifuSummary]],
      RegisteredAPIMessageFunctions.api[TournamentPaifuGetAPIMessage, Paifu]
    )
